name: ccs_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.10.0
  cloud_firestore: ^6.5.0
  firebase_storage: ^13.4.2
  firebase_auth: ^6.5.2
  firebase_messaging: ^16.3.0

  cupertino_icons: ^1.0.8
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  google_sign_in: ^7.2.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  image: ^4.8.0
  path_provider: ^2.1.5

  # Use 2.2.2 because geocoding 3.x can force geocoding_android to compile
  # against an incompatible Android SDK in this project.
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/bg.png
    - assets/bg_map.png
    - assets/spot_icons/
    - assets/user_cars/
    - assets/ccs_logo.png
