// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwWJxI62wQQQLF0TSWtvFpC0PIZZ61mOY',
    appId: '1:325709324670:web:31cf6660554564f1cf532f',
    messagingSenderId: '325709324670',
    projectId: 'ccsv1-63537',
    authDomain: 'ccsv1-63537.firebaseapp.com',
    storageBucket: 'ccsv1-63537.firebasestorage.app',
    measurementId: 'G-914JBCVY4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjkQKixwpNCi54dnq4XHP6MpuETs4y4us',
    appId: '1:325709324670:android:1233148549f6c785cf532f',
    messagingSenderId: '325709324670',
    projectId: 'ccsv1-63537',
    storageBucket: 'ccsv1-63537.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApfyLNWzsYyf4JIP6ZR6WoCKFpuLq7EBU',
    appId: '1:325709324670:ios:9ed0c01647554e66cf532f',
    messagingSenderId: '325709324670',
    projectId: 'ccsv1-63537',
    storageBucket: 'ccsv1-63537.firebasestorage.app',
    iosBundleId: 'lv.ilexall.ccs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApfyLNWzsYyf4JIP6ZR6WoCKFpuLq7EBU',
    appId: '1:325709324670:ios:9ed0c01647554e66cf532f',
    messagingSenderId: '325709324670',
    projectId: 'ccsv1-63537',
    storageBucket: 'ccsv1-63537.firebasestorage.app',
    iosBundleId: 'lv.ilexall.ccs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwWJxI62wQQQLF0TSWtvFpC0PIZZ61mOY',
    appId: '1:325709324670:web:322a14f11c19011fcf532f',
    messagingSenderId: '325709324670',
    projectId: 'ccsv1-63537',
    authDomain: 'ccsv1-63537.firebaseapp.com',
    storageBucket: 'ccsv1-63537.firebasestorage.app',
    measurementId: 'G-ZGZKZ83EY0',
  );
}
